# Generated by Django 5.2.7 on 2025-10-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulaweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
        migrations.AddField(
            model_name='usuario',
            name='curso',
            field=models.CharField(blank=True, db_column='curso', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, db_column='data_nascimento', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, db_column='email', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(blank=True, db_column='endereco', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='semestre',
            field=models.IntegerField(blank=True, db_column='semestre', null=True),
        ),
    ]
