# Generated by Django 5.2.7 on 2025-11-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulaweb', '0002_remove_usuario_telefone_usuario_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, db_column='banner', null=True, upload_to='eventos_banners/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, db_column='telefone', max_length=20, null=True),
        ),
    ]
