# Generated by Django 5.2.7 on 2025-10-03 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_column='tipo', max_length=50)),
                ('data_inicio', models.DateField(db_column='data_inicio')),
                ('data_fim', models.DateField(db_column='data_fim')),
                ('horario', models.TimeField(db_column='horario')),
                ('local', models.CharField(db_column='local', max_length=100)),
                ('qtd_participantes', models.IntegerField(db_column='qtd_participantes')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'evento',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='nome', max_length=100)),
                ('telefone', models.CharField(blank=True, db_column='telefone', max_length=20, null=True)),
                ('instituicao', models.CharField(blank=True, db_column='instituicao', max_length=100, null=True)),
                ('login', models.CharField(db_column='login', max_length=50, unique=True)),
                ('senha', models.CharField(db_column='senha', max_length=255)),
                ('perfil', models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('organizador', 'Organizador')], db_column='perfil', max_length=20)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, db_column='data_inscricao')),
                ('evento', models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='aulaweb.evento')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='aulaweb.usuario')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'db_table': 'inscricao',
                'ordering': ['-data_inscricao'],
                'unique_together': {('usuario', 'evento')},
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, db_column='data_emissao')),
                ('inscricao', models.ForeignKey(db_column='id_inscricao', on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='aulaweb.inscricao')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'db_table': 'certificado',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(db_column='id_organizador', on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='aulaweb.usuario'),
        ),
    ]
