# Generated by Django 6.0 on 2025-12-08 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulaweb', '0003_evento_banner_usuario_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aulaweb.usuario')),
            ],
            options={
                'db_table': 'log_auditoria',
                'ordering': ['-data_hora'],
            },
        ),
    ]
