# Generated by Django 6.0 on 2025-12-08 02:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulaweb', '0004_logauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(db_column='ativo', default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.UUIDField(db_column='token', default=uuid.uuid4, editable=False),
        ),
    ]
