# Generated by Django 6.0 on 2025-12-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulaweb', '0005_usuario_ativo_usuario_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='certificado_emitido',
            field=models.BooleanField(default=False),
        ),
    ]
