# Generated by Django 6.0 on 2025-12-09 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulaweb', '0006_inscricao_certificado_emitido'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_responsavel', to='aulaweb.usuario'),
        ),
    ]
