# Generated by Django 6.0 on 2025-12-09 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulaweb', '0007_evento_responsavel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logauditoria',
            options={},
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aulaweb.usuario'),
        ),
        migrations.AlterModelTable(
            name='logauditoria',
            table=None,
        ),
    ]
